project_id = "pomvsimhphgbqxreyhfp"

[functions.chat-support]
verify_jwt = false

[functions.analyze-ticket-priority]
verify_jwt = false

[functions.suggest-ticket-reply]
verify_jwt = false

[functions.ally-chat]
verify_jwt = true

[functions.blog-ai-assistant]
verify_jwt = true

[functions.publish-scheduled-posts]
verify_jwt = false
